#!/bin/bash

# Stop the test if anything breaks
set -e

# To set up for the test environment, we need to build and run the latest state of the base image, then test it by
# running a set of API calls to it.

# A unique name that we'll delete later, for the docker
timestamp=$(date +%s%3N)

# Build and tag the Docker image
docker build -t "connectord-base-test:$timestamp" .

# We need a random port to bind to the container. Keep trying ports until we find a free one.
port=$(shuf -i 50000-59999 -n 1)
while lsof -i :"$port" > /dev/null 2>&1; do
  port=$((port + 1))
done

# Run the container
container_id=$(docker run -d -p "$port:80" "connectord-base-test:$timestamp")
echo "Test container running on port $port"
export connectord_test_port=$port

# Wait 2 seconds for everything in the container to start
sleep 2

# Run all the tests in order
php ./tests/Base.php

# And we're done! Shut down the test container and clean up
docker stop $container_id
docker rm $container_id
docker rmi connectord-base-test:$timestamp

echo "Test run completed"